controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_product_by_category:
    path: '/product/category/{id}'
    controller: 'App\Controller\ProductController::productsByCategory'
    methods: ['GET']